deliriumm/api/urls.py
from django.urls import path, include
from . import views
from rest_framework import routers


app_name = "api"

router = routers.DefaultRouter()
router.register(r'ticket', views.TicketViewSet)
router.register(r'ticketrequest', views.TicketRequestViewSet)
router.register(r'eventaccount', views.EventAccountViewSet)

urlpatterns = [
    path('', include(router.urls)),
    path('api-auth/', include('rest_framework.urls'))
]

deliriumm/core/urls.py
from django.urls import path

from . import views


app_name = "core"
urlpatterns = [
    path("", views.index, name="index"),
    path("dashboard/", views.dashboard, name="dashboard"),
    path("events/", views.events, name="events"),
    path("staff/", views.staff_view, name="staff_view"),
    path("admin/", views.admin_view, name="admin_view"),
    path("admin/rps_cash/", views.rps_cash_view, name="rps_cash_view"),
    path("admin/rps_all/", views.alltickets, name="rps_all"),
    path("material/dowload/<int:pk>", views.download_material, name="dowload_material"),
    path("material/delete/<int:pk>", views.delete_material, name="delete_material"),
    path("material/upload/", views.upload_material, name="upload_material")
]

deliriumm/deliriumm/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("users/", include("users.urls")),
    path("core/", include("core.urls")),
    path("", include("mainpage.urls")),
    path("core/tickets/", include("tickets.urls")),
    path("api/", include("api.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

deliriumm/mainpage/urls.py
from django.urls import path

from . import views


app_name = "mainpage"
urlpatterns = [
    path("", views.index, name="index"),
]

deliriumm/tickets/urls.py
from django.urls import path

from . import views


app_name = "tickets"
urlpatterns = [
    path("", views.index, name="index"),
    path("my_tickets", views.my_tickets, name="my_tickets"),
    path("t/export/<str:hash>", views.temp_ticket_export, name="temp_ticket_export"),
    path("t/requestall/<str:requestid>", views.image_tickets, name="image_tickets"),
    path("t/image/<str:hash>", views.image_ticket, name="image_ticket"),
    path("t/download/<str:tickethash>", views.download_ticket, name="download_ticket"),
    path("r/<int:requestid>", views.request_view, name="request_view"),
    path("r/new", views.create_request_view, name="create_request_view"),
    path("r/new/create", views.new_ticket_request, name="new_ticket_request"),
    path("r/<int:requestid>/delete", views.delete_ticket_request, name="delete_ticket_request"),
    path("a/<int:requestid>", views.admin_request_view, name="admin_request_view"),
    path("a/<int:requestid>/ap", views.aprobar_request, name="aprobar_request"),
    path("a/<int:requestid>/re", views.rechazar_request, name="rechazar_request"),
    path("a/<int:requestid>/ar", views.archivar_request, name="archivar_request"),
    path("a/<int:requestid>/as", views.asignar_request, name="asignar_request"),
    path("a/<int:requestid>/togglecash", views.toggleCash, name="togglecash"),
]

deliriumm/users/urls.py
from django.urls import path

from . import views


app_name = "users"
urlpatterns = [
    path("", views.index, name="index"),
    path("login/", views.login_view, name="login"),
    path("logout/", views.logout_view, name="logout"),
    path("profile/", views.profile, name="profile"),
    path("settings/", views.settings, name="settings"),
    path("u/<str:username>", views.public_profile, name="public_profile"),
    path("register/", views.register, name="register")
]

deliriumm/users/models.py
from django.contrib.auth.models import AbstractUser
from django.utils import timezone
from django.db import models
from django.contrib.auth.models import User
 
# User class
class UserCore(models.Model):

    user = models.OneToOneField(User, on_delete=models.CASCADE)
    phonenum = models.CharField(verbose_name="Numero de Cel", blank=True, max_length=16)
    instagram = models.CharField(verbose_name="Instagram Username", blank=True, max_length=50)

    def __str__(self) -> str:
        return str(self.user)
    class Meta:
         
        permissions = (
            ("can_view_admin", "To see admin pages"),
            ("can_view_staff", "To see staff pages"),
            ("can_view_rp", "To see rp PAGES"),
        )
    last_ticket_request_see = models.IntegerField(verbose_name="Última Ticket Request visitada", default=0)
# Add other custom permissions according to need.

class RegToken(models.Model):
    username = models.CharField(max_length=50, primary_key=True)
    token = models.CharField(max_length=20)

    

deliriumm/users/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.shortcuts import get_object_or_404
from .models import RegToken, UserCore
from django.contrib.auth.models import Group



# Create your views here.

# /users/     REDIRECT TO LOGIN OR CORE HOME
def index(request):
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse("users:login"))
    return HttpResponseRedirect(reverse("users:profile"))


# /users/profile  IFNOT LOGIN REDIRECT TO LOGIN // RENDER USER.HTML (PROFILE PAGE)
def profile(request):
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse("users:login"))
    return render(request, "users/profile.html", {
        "user": request.user
    })

# /users/u/<username> IFNOT LOGIN REDIRECTO TO LOGIN // GET <USERNAME> IF NOT 404 //
# 
# USERP = REQUEST.USER --> PROFILE /
# IFNOT RENDER PUBLIC PROFILE

def public_profile(request, username):
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse("users:login"))
    prof_user = get_object_or_404(User, username=username)
    if prof_user == request.user:
        return HttpResponseRedirect(reverse('users:profile'))
    return render(request, "users/public_profile.html", {
        "user": request.user,
        "profile_user": prof_user
    })


def register(request):
    if request.user.is_authenticated:
        return HttpResponseRedirect(reverse("core:index"))
    
    if request.POST:
        if request.POST.get('token', False):
            try:
                token = RegToken.objects.get(token=request.POST.get('token', False))
            except(BaseException):
                return render(request, "users/token_register.html", {
                    "message": "Token Invalido"
        })
            username = token.username
            token.delete()
            form = UserCreationForm()
            return render(request, "users/register.html",{
                'form': form,
                "username": username

        })



        else:
            form = UserCreationForm(request.POST)
            if form.is_valid():
                form.save()
                username = form.cleaned_data.get('username')
                raw_password = form.cleaned_data.get('password1')
                user = authenticate(username=username, password=raw_password)
                login(request, user)
                if not UserCore.objects.filter(user=user):
                    uc = UserCore(user=user).save()
                my_group = Group.objects.get(name='Rp') 
                my_group.user_set.add(user)
                return redirect('core:index')
            else:
                return render(request, "users/register.html", {
                    "message": "Error de registro!"
        })
        return render(request, "users/token_register.html", {
                    "message": "Token Invalido"
        })
    else:
        return render(request, "users/token_register.html", {
        })
        


# /users/settings
def settings(request):
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse("users:login"))
    if request.POST:
        user= request.user
        if request.POST.get('username', False):
            user.username = request.POST['username']
        if request.POST.get('first_name', False):
            user.first_name = request.POST.get('first_name')
        if request.POST.get('last_name', False):   
            request.user.last_name = request.POST['last_name']
        if request.POST.get('email', False):   
            request.user.email = request.POST['email']
        if request.POST.get('phonenum', False):   
            request.user.usercore.phonenum = request.POST['phonenum']
        if request.POST.get('instagram', False):   
            request.user.usercore.instagram = request.POST['instagram']
        request.user.usercore.save()
        user.save()
        return render(request, "users/settings.html", {
            "user": request.user,
            "message": "¡Información actualizada!",
        })
    return render(request, "users/settings.html", {
        "user": request.user
    })



# /users/login
def login_view(request):
    if request.method == "POST":
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            if not UserCore.objects.filter(user=request.user):
                uc = UserCore(user=request.user).save()
            return HttpResponseRedirect(reverse("core:index"))
        else:
            return render(request, "users/login.html", {
                "message": "Invalid credentials"
            })
    return render(request, "users/login.html")


# /users/logout
def logout_view(request):
    logout(request)
    return render(request, "users/login.html", {
        "message": "Logged out."
    })

deliriumm/users/templates/users/layout_1.html
<!DOCTYPE html>
<html lang="en">
    <head>
        {% load static %}

        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
        <link rel="stylesheet" type="text/css" href="{% static 'users/style_layout1.css' %}">
        
        {% block head %}
        {% endblock %}

    </head>
    <body>
      <header>

        <ul class="nav justify-content-center">
            <li class="nav-item">
              <a class="nav-link" aria-current="page" href="{% url 'core:index' %}" id="deliriumm">Deliriumm</a>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-expanded="false">Core</a>
              <ul class="dropdown-menu">
                <li><a class="dropdown-item" href="{% url 'core:dashboard' %}">Dashboard</a></li>
                <li><a class="dropdown-item" href="{% url 'core:events' %}">Eventos</a></li>
                <li><a class="dropdown-item" href="{% url 'users:settings' %}">Soporte</a></li>
                <li><hr class="dropdown-divider"></li>
                <li><a class="dropdown-item" href="{% url 'core:staff_view' %}">Staff</a></li>
                <li><hr class="dropdown-divider"></li>
                <li><a class="dropdown-item" href="{% url 'core:admin_view' %}">Admin</a></li>
              </ul>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'tickets:index' %}">Tickets</a>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-expanded="false">Mi Cuenta</a>
                <ul class="dropdown-menu">
                  <li><a class="dropdown-item disabled" href="#">¡Hola, {{ user.first_name }}!</a></li>
                  <li><a class="dropdown-item" href="{% url 'users:profile' %}">Perfil</a></li>
                  <li><a class="dropdown-item" href="{% url 'users:settings' %}">Configuración</a></li>
                  <li><hr class="dropdown-divider"></li>
                  <li><a class="dropdown-item" href="{% url 'users:logout' %}">Log Out</a></li>
                </ul>
              </li>
          </ul>

    </header>

        <div class="container">
        {% block body %}
        
        {% endblock body %}
      </div>

        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

    </body>
</html>

deliriumm/users/templates/users/login.html
<!DOCTYPE html>
<html lang="en">
    <head>
        {% load static %}
        <title>Login - Deliriumm</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
        <link rel="stylesheet" type="text/css" href="{% static 'users/style_login.css' %}">
        
    </head>
    <body>
        <h1 id="deliriumm" class="mt-4 mb-2">DELIRIUMM</h1>

        {% if message %}
            <div id="message">{{ message }}</div>
        {% endif %}
    
        <div class="container">
            <form id="formlogin" action="{% url 'users:login' %}" method="post">
                {% csrf_token %}
                <div class="form-floating mb-3">
                    <input type="text" name="username" class="form-control" id="floatingInput" placeholder="Username">
                    <label for="floatingInput">Username</label>
                </div>
                <div class="form-floating">
                    <input type="password" name="password" class="form-control" id="floatingPassword" placeholder="Password">
                    <label for="floatingPassword">Password</label>
                </div>
                <div class="d-grid justify-content-center mt-3">
                    <button type="submit" class="btn btn-primary text-center">Login</button>
                  </div>
            </form>
        </div>
        <div align="left" id="footerdiv">
            <a style="color: white" href="{% url 'mainpage:index' %}">Regresar al Inicio</a>
        </div>

        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

    </body>
</html>

deliriumm/users/templates/users/profile.html
{% extends 'users/layout_1.html' %}

{% block head %}

<title>Perfil - Deliriumm Core</title>

{% endblock head %}

{% block body %}

<h1>Perfil</h1>

<h4>Nombre: {{ user.first_name }}</h4>
<h4>Apellidos: {{ user.last_name }}</h4>
<h4>Username: {{ user.username }}</h4>
<h4>Correo: {{ user.email }}</h4>
<h4>Teléfono: {{ user.usercore.phonenum }}</h4>
<h4>Instagram: @{{ user.usercore.instagram }}</h4>

<a href="{% url 'users:settings' %}">Editar mis datos</a>

{% endblock body %}

deliriumm/users/templates/users/public_profile.html
{% extends 'users/layout_1.html' %}

{% block head %}

<title>Perfil - Deliriumm Core</title>

{% endblock head %}

{% block body %}

<h1>Perfil Publico (PARA LOS DEMAS)</h1>

<p>Muestra mis datos publicos</p>
<p>{{ profile_user.first_name }}</p>

{% endblock body %}

deliriumm/users/templates/users/register.html
<!DOCTYPE html>
<html lang="en">
    <head>
        {% load static %}
        <title>Register - Deliriumm</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
        <link rel="stylesheet" type="text/css" href="{% static 'users/style_register.css' %}">
        
    </head>
    <body>

      {% if message %}
      <div id="message">{{ message }}</div>
      {% endif %}

        <h1 id="deliriumm" class="mt-4 mb-2">DELIRIUMM</h1>
        <div class="container">
            <h2>Username recomendado: {{ username }}</h2>
            <form method="post">
                {% csrf_token %}
                {% for field in form %}
                  <p>
                    {{ field.label_tag }}<br>
                    {{ field }}
                    {% if field.help_text %}
                      <small style="color: grey">{{ field.help_text }}</small>
                    {% endif %}
                    {% for error in field.errors %}
                      <p style="color: red">{{ error }}</p>
                    {% endfor %}
                  </p>
                {% endfor %}
                <button type="submit">Registarse</button>
              </form>
        </div>


        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

    </body>
</html>

deliriumm/users/templates/users/settings.html
{% extends 'users/layout_1.html' %}

{% block head %}

<title>Ajustes - Deliriumm Core</title>

{% endblock head %}

{% block body %}

<h1>Configuración</h1>

<p>Editar datos personales</p>

{% if message %}
<div class="alert alert-success" role="alert">
  {{ message }}
</div>
{% endif %}
  
<form action="" method="post"> 
  {% csrf_token %}
  <div class="input-group mb-3">
    <span class="input-group-text" id="basic-addon1">@</span>
    <input type="text" name="username" class="form-control" placeholder="Username" aria-label="Username" aria-describedby="basic-addon1" value="{{ user.username }}">
  </div>
  <div class="input-group mb-3">
    <span class="input-group-text" id="basic-addon1">Email</span>
    <input type="email" name="email" class="form-control" placeholder="example@example.com"id="exampleInputEmail1" aria-describedby="emailHelp" value="{{ user.email }}">
  </div>
  
  <div class="input-group mb-3">
    <span class="input-group-text" id="basic-addon1">Nombre</span>
    <input type="text" name="first_name" class="form-control" placeholder="Nombre" aria-label="Nombre" aria-describedby="basic-addon1" value="{{ user.first_name }}">
  </div>

  <div class="input-group mb-3">
    <span class="input-group-text" id="basic-addon1">Apellidos</span>
    <input type="text" name="last_name" class="form-control" placeholder="Apellidos" aria-label="Apellidos" aria-describedby="basic-addon1" value="{{ user.last_name }}">
  </div>
  <div class="input-group mb-3">
    <span class="input-group-text" id="basic-addon1">Teléfono</span>
    <input type="text" name="phonenum" class="form-control" placeholder="Teléfono" aria-label="Teléfono" aria-describedby="basic-addon1" value="{{ user.usercore.phonenum }}">
  </div>
  <div class="input-group mb-3">
    <span class="input-group-text" id="basic-addon1">@</span>
    <input type="text" name="instagram" class="form-control" placeholder="Instagram" aria-label="Instagram" aria-describedby="basic-addon1" value="{{ user.usercore.instagram }}">
  </div>

  <button type="submit" class="btn btn-primary text-center">Guardar</button>
</form>

  

{% endblock body %}

deliriumm/users/templates/users/token_register.html
<!DOCTYPE html>
<html lang="en">
    <head>
        {% load static %}
        <title>Token Check - Deliriumm</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
        <link rel="stylesheet" type="text/css" href="{% static 'users/style_login.css' %}">
        
    </head>
    <body>
        <h1 id="deliriumm" class="mt-4 mb-2">DELIRIUMM</h1>

        {% if message %}
            <div id="message">{{ message }}</div>
        {% endif %}
    
        <div class="container">
            <form id="formlogin" action="" method="post">
                {% csrf_token %}
                <div class="form-floating mb-3">
                    <input type="text" name="token" class="form-control" id="floatingInput" placeholder="Token">
                    <label for="floatingInput">Token</label>
                </div>
                <div class="d-grid justify-content-center mt-3">
                    <button type="submit" class="btn btn-primary text-center">Continuar</button>
                  </div>
            </form>

        </div>

        

        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

    </body>
</html>