deliriumm/api/urls.py
from django.urls import path, include
from . import views
from rest_framework import routers


app_name = "api"

router = routers.DefaultRouter()
router.register(r'ticket', views.TicketViewSet)
router.register(r'ticketrequest', views.TicketRequestViewSet)
router.register(r'eventaccount', views.EventAccountViewSet)

urlpatterns = [
    path('', include(router.urls)),
    path('api-auth/', include('rest_framework.urls'))
]

deliriumm/core/urls.py
from django.urls import path

from . import views


app_name = "core"
urlpatterns = [
    path("", views.index, name="index"),
    path("dashboard/", views.dashboard, name="dashboard"),
    path("events/", views.events, name="events"),
    path("staff/", views.staff_view, name="staff_view"),
    path("admin/", views.admin_view, name="admin_view"),
    path("admin/rps_cash/", views.rps_cash_view, name="rps_cash_view"),
    path("admin/rps_all/", views.alltickets, name="rps_all"),
    path("material/dowload/<int:pk>", views.download_material, name="dowload_material"),
    path("material/delete/<int:pk>", views.delete_material, name="delete_material"),
    path("material/upload/", views.upload_material, name="upload_material")
]

deliriumm/deliriumm/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("users/", include("users.urls")),
    path("core/", include("core.urls")),
    path("", include("mainpage.urls")),
    path("core/tickets/", include("tickets.urls")),
    path("api/", include("api.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

deliriumm/tickets/urls.py
from django.urls import path

from . import views


app_name = "tickets"
urlpatterns = [
    path("", views.index, name="index"),
    path("my_tickets", views.my_tickets, name="my_tickets"),
    path("t/export/<str:hash>", views.temp_ticket_export, name="temp_ticket_export"),
    path("t/requestall/<str:requestid>", views.image_tickets, name="image_tickets"),
    path("t/image/<str:hash>", views.image_ticket, name="image_ticket"),
    path("t/download/<str:tickethash>", views.download_ticket, name="download_ticket"),
    path("r/<int:requestid>", views.request_view, name="request_view"),
    path("r/new", views.create_request_view, name="create_request_view"),
    path("r/new/create", views.new_ticket_request, name="new_ticket_request"),
    path("r/<int:requestid>/delete", views.delete_ticket_request, name="delete_ticket_request"),
    path("a/<int:requestid>", views.admin_request_view, name="admin_request_view"),
    path("a/<int:requestid>/ap", views.aprobar_request, name="aprobar_request"),
    path("a/<int:requestid>/re", views.rechazar_request, name="rechazar_request"),
    path("a/<int:requestid>/ar", views.archivar_request, name="archivar_request"),
    path("a/<int:requestid>/as", views.asignar_request, name="asignar_request"),
    path("a/<int:requestid>/togglecash", views.toggleCash, name="togglecash"),
]

deliriumm/users/urls.py
from django.urls import path

from . import views


app_name = "users"
urlpatterns = [
    path("", views.index, name="index"),
    path("login/", views.login_view, name="login"),
    path("logout/", views.logout_view, name="logout"),
    path("profile/", views.profile, name="profile"),
    path("settings/", views.settings, name="settings"),
    path("u/<str:username>", views.public_profile, name="public_profile"),
    path("register/", views.register, name="register")
]

deliriumm/core/models.py
from asyncio import events
from pydoc import describe
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Event(models.Model):
    name = models.CharField(verbose_name="Name", max_length=200)
    datetime = models.DateTimeField(verbose_name="Date, Time")
    price = models.IntegerField(verbose_name="Price")
    max_tickets = models.IntegerField(verbose_name="Max Tickets", blank=True, default=0)
    locationmapslink = models.CharField(max_length=300, verbose_name="Google Maps Link", blank=True)

    STATUS = ( 
        ("AN", "Anunciado"), 
        ("VE", "En Venta"), 
        ("TE", "Venta Terminada"), 
        ("AR", "Archivado"), 
    ) 
    status = models.CharField(
        max_length=2,
        choices=STATUS,
        default='AN',
    )

    def __str__(self):
        return str(self.pk) + " - " + self.name


class Material(models.Model):
    description = models.CharField(max_length=200)
    file = models.FileField(verbose_name="Archivo", upload_to='uploads/materials/', blank=True)
    event = models.ForeignKey(Event, on_delete=models.CASCADE)

class Task(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now=True)
    finish = models.BooleanField(default=False)
    description = models.CharField(max_length=300, blank=True)
    file1 = models.FileField(upload_to='uploads/tasks/')
    file2 = models.FileField(upload_to='uploads/tasks/')
    file3 = models.FileField(upload_to='uploads/tasks/')


class EventAccount(models.Model):
    username = models.CharField(max_length=100, blank=True)
    name = models.CharField(max_length=100, blank=True)
    password = models.CharField(max_length=100, blank=True)
    
class EventSell(models.Model):
    eventaccount = models.ForeignKey(EventAccount, on_delete=models.CASCADE)
    total = models.IntegerField(blank=True, default=0)
    datetime = models.DateTimeField(auto_now=True)


class EventItemType(models.Model):
    name = models.CharField(max_length=100, blank=False)
    description = models.CharField(max_length=200, blank=True)
    price = models.IntegerField(blank=False)

    def __str__(self):
        return str(self.pk) + " - " + self.name

class EventItem(models.Model):
    type = models.ForeignKey(EventItemType, on_delete=models.CASCADE)
    eventsell = models.ForeignKey(EventSell, on_delete=models.CASCADE)
    

deliriumm/core/views.py
import mimetypes
import os
from django.conf import settings
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse
from django.contrib.auth.models import User
from tickets.models import Ticket, TicketRequest
from django.db.models import Q

from users.models import UserCore

from .models import Event, Material

# Create your views here.

def download_material(request, pk):
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse("users:login"))
    path1 = get_object_or_404(Material, pk=pk).file
    # Define text file name
    filename = str(path1)
    # Define the full file path
    filepath = settings.MEDIA_ROOT + filename
    # Open the file for reading content
    with open(filepath, 'rb') as f:
       path = f.read()
    # Set the mime type
    mime_type, _ = mimetypes.guess_type(filepath)
    # Set the return value of the HttpResponse
    response = HttpResponse(path, content_type=mime_type)
    # Set the HTTP header for sending to browser
    response['Content-Disposition'] = "attachment; filename=%s" % filename
    # Return the response value
    return response

def delete_material(request, pk):
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse("users:login"))
    if request.user.has_perm('users.can_view_admin'):
        if os.path.exists(settings.MEDIA_ROOT + str(Material.objects.get(pk=pk).file)):
            os.remove(settings.MEDIA_ROOT + str(Material.objects.get(pk=pk).file))
        Material.objects.get(pk=pk).delete()
        return redirect('core:admin_view')
    return HttpResponseRedirect(reverse("users:login"))


#--------------------------------------------------------------------
def index(request):
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse("users:login"))
    return render(request, "core/index.html", {
        "event": Event.objects.get(status="VE")
    })
#--------------------------------------------------------------------


#--------------------------------------------------------------------
def dashboard(request):
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse("users:login"))
    return render(request, "core/dashboard.html")
#--------------------------------------------------------------------


#--------------------------------------------------------------------
def events(request):
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse("users:login"))
    return render(request, "core/events.html", {
        "events": Event.objects.all()
    })
#--------------------------------------------------------------------

# -- STAFF --

#--------------------------------------------------------------------
def staff_view(request):
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse("users:login"))
    usercore = get_object_or_404(UserCore, user=request.user)
    if request.user.has_perm('users.can_view_staff') or request.user.has_perm('users.can_view_admin'):
        return render(request, "core/staff/index.html", {
            "tickets_pe": TicketRequest.objects.filter(status="PE"),
            "tickets_re": TicketRequest.objects.filter(status="RE"),
            "tickets_va": TicketRequest.objects.filter(status="VA"),
            "tickets_ar": TicketRequest.objects.filter(status="AR"),
            "last_ticket": usercore.last_ticket_request_see,
        }) 

    else:
        return HttpResponseRedirect(reverse('users:login'))
#--------------------------------------------------------------------


#--------------------------------------------------------------------
def materialCreate(request, event):
    m = Material(description=request.POST['description'], file=request.FILES['material'], event=event)
    return m


def upload_material(request):
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse("users:login"))
    event = get_object_or_404(Event, status="VE")
    if request.POST:
        try:
            m = materialCreate(request=request, event=event)
        except (BaseException):
            return render(request, "core/admin/upload_material.html",
            {
                "error_message": "¡Ha occurído un error!",
                "event": event
            })
        else:
            m.save()
            return HttpResponseRedirect(reverse("core:admin_view"))
    else:
        return render(request, "core/admin/upload_material.html", {
            "event": event,
        })
#--------------------------------------------------------------------
        





# -- ADMIN --

#--------------------------------------------------------------------
def admin_view(request):
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse("users:login"))
    usercore = get_object_or_404(UserCore, user=request.user)
    ticketsbank = TicketRequest.objects.filter(Q(payment_method="CARD") | Q(payment_method="TRANSFER") | Q(payment_method="DEPOSIT") & Q(status="VA"))
    totalbank = 0
    for ticket in ticketsbank:
        totalbank = totalbank + ticket.total
    if request.user.has_perm('users.can_view_admin'):
        return render(request, "core/admin/index.html", {
            "tickets_pe": TicketRequest.objects.filter(status="PE"),
            "tickets_re": TicketRequest.objects.filter(status="RE"),
            "tickets_va": TicketRequest.objects.filter(status="VA"),
            "tickets_ar": TicketRequest.objects.filter(status="AR"),
            "event": Event.objects.get(status="VE"),
            "last_ticket": usercore.last_ticket_request_see,
            "requests_cash": TicketRequest.objects.filter(Q(payment_method="CASH") &  Q(status="VA")),
            "total_bank": totalbank
            
        }) 

    else:
        return HttpResponseRedirect(reverse('users:login'))
#--------------------------------------------------------------------


#--------------------------------------------------------------------
def rps_cash_view(request):
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse("users:login"))
    usercore = get_object_or_404(UserCore, user=request.user)

    

    cashrequests_notpay = {}

    users = User.objects.all()

    for user in users:
        userrequestpay = []
        username = user.username
        ticketrequests = user.ticketrequest_set.all()
        if ticketrequests:
            for ticketrequest in ticketrequests:
                if ticketrequest.payment_method == "CASH":
                    if ticketrequest.status == "VA":
                        if ticketrequest.cash_pay == False:
                            userrequestpay.append(int(ticketrequest.pk))
                            cashrequests_notpay[username] = userrequestpay
            


    # if keys & values:
    #     for i in range(len(keys)):
    #             cashrequests[keys[i]] = values[i]

            
    #         print(dicts)

    #for users
    ticketsallcash = TicketRequest.objects.filter(Q(payment_method="CASH") &  Q(status="VA"))
    cashtotal = 0
    ticketnotpay = ticketsallcash.filter(cash_pay=False)
    cashnotpay = 0

    for ticket in ticketsallcash:
        cashtotal = cashtotal + ticket.total
    for ticket in ticketnotpay:
        cashnotpay = cashnotpay + ticket.total
    

    if request.user.has_perm('users.can_view_admin'):
        return render(request, "core/admin/rps_cash.html", {
            "event": Event.objects.get(status="VE"),
            "last_ticket": usercore.last_ticket_request_see,
            "cashrequests": cashrequests_notpay.items(),
            "allrequests": TicketRequest.objects.all(),
            "cashtotal": cashtotal,
            "cashnotpay": cashnotpay,
            "cashpay": cashtotal-cashnotpay,
        }) 

    else:
        return HttpResponseRedirect(reverse('users:login'))


def alltickets(request):
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse("users:login"))
    usercore = get_object_or_404(UserCore, user=request.user)

    rp_alltickets = {}

    users = User.objects.all()

    for user in users:
        tickets = user.ticket_set.all()
        countu = tickets.count()
        rp_alltickets[user.username] = countu


    if request.user.has_perm('users.can_view_admin'):
        return render(request, "core/admin/alltickets.html", {
            "event": Event.objects.get(status="VE"),
            "rp_alltickets": rp_alltickets.items()
        }) 

    else:
        return HttpResponseRedirect(reverse('users:login'))

deliriumm/core/templates/core/dashboard.html
{% extends 'core/layout_1.html' %}

{% block head %}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'core/style_index.css' %}">
<title>Dashboard - Deliriumm Core</title>

{% endblock %}

{% block body %}

<h1>CORE - Dashboard</h1>

<p>¡Bienvenid@, {{ user.first_name }}!</p>

<div class="row">

    <!-- Earnings (Monthly) Card Example -->
    <div class="col-xl-3 col-md-6 mb-4">
        <div class="card border-left-primary shadow h-100 py-2">
            <div class="card-body">
                <div class="row no-gutters align-items-center">
                    <div class="col mr-2">
                        <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">
                            Earnings (Monthly)</div>
                        <div class="h5 mb-0 font-weight-bold text-gray-800">$40,000</div>
                    </div>
                    <div class="col-auto">
                        <i class="fas fa-calendar fa-2x text-gray-300"></i>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Earnings (Monthly) Card Example -->
    <div class="col-xl-3 col-md-6 mb-4">
        <div class="card border-left-success shadow h-100 py-2">
            <div class="card-body">
                <div class="row no-gutters align-items-center">
                    <div class="col mr-2">
                        <div class="text-xs font-weight-bold text-success text-uppercase mb-1">
                            Earnings (Annual)</div>
                        <div class="h5 mb-0 font-weight-bold text-gray-800">$215,000</div>
                    </div>
                    <div class="col-auto">
                        <i class="fas fa-dollar-sign fa-2x text-gray-300"></i>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="row">

    <!-- Earnings (Monthly) Card Example -->
    <div class="col-xl-3 col-md-6 mb-4">
        <div class="card border-left-info shadow h-100 py-2">
            <div class="card-body">
                <div class="row no-gutters align-items-center">
                    <div class="col mr-2">
                        <div class="text-xs font-weight-bold text-info text-uppercase mb-1">Tasks
                        </div>
                        <div class="row no-gutters align-items-center">
                            <div class="col-auto">
                                <div class="h5 mb-0 mr-3 font-weight-bold text-gray-800">50%</div>
                            </div>
                            <div class="col">
                                <div class="progress progress-sm mr-2">
                                    <div class="progress-bar bg-info" role="progressbar"
                                        style="width: 50%" aria-valuenow="50" aria-valuemin="0"
                                        aria-valuemax="100"></div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-auto">
                        <i class="fas fa-clipboard-list fa-2x text-gray-300"></i>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Pending Requests Card Example -->
    <div class="col-xl-3 col-md-6 mb-4">
        <div class="card border-left-warning shadow h-100 py-2">
            <div class="card-body">
                <div class="row no-gutters align-items-center">
                    <div class="col mr-2">
                        <div class="text-xs font-weight-bold text-warning text-uppercase mb-1">
                            Pending Requests</div>
                        <div class="h5 mb-0 font-weight-bold text-gray-800">18</div>
                    </div>
                    <div class="col-auto">
                        <i class="fas fa-comments fa-2x text-gray-300"></i>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


<div class="card shadow mb-4">
    <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">Development Approach</h6>
    </div>
    <div class="card-body">
        <p>SB Admin 2 makes extensive use of Bootstrap 4 utility classes in order to reduce
            CSS bloat and poor page performance. Custom CSS classes are used to create
            custom components and custom utility classes.</p>
        <p class="mb-0">Before working with this theme, you should become familiar with the
            Bootstrap framework, especially the utility classes.</p>
    </div>
</div>

<div class="container" id="list">
    <ol class="list-group list-group-numbered">

        <li class="list-group-item d-flex justify-content-between align-items-start">
          <div class="ms-2 me-auto">
            <div class="fw-bold">Subheading</div>
            Content for list item
          </div>
          <span class="badge bg-primary rounded-pill">14</span>
        </li>
        <li class="list-group-item d-flex justify-content-between align-items-start">
          <div class="ms-2 me-auto">
            <div class="fw-bold">Subheading</div>
            Content for list item
          </div>
          <span class="badge bg-primary rounded-pill">14</span>
        </li>
      </ol>
</div>

<div class="container">
    <div class="row row-cols-5 ">
      <div class="col">Column</div>
      <div class="col">Column</div>
      <div class="col">Column</div>
      <div class="col">Column</div>
      <div class="col">Column</div>
      <div class="col">Column</div>
      <div class="col">Column</div>
      <div class="col">Column</div>
      <div class="col">Column</div>
      <div class="col">Column</div>
      <div class="col">Column</div>
      <div class="col">Column</div>
      <div class="col">Column</div>
      <div class="col">Column</div>
    </div>
  </div>

  <div class="row">

    <div class="col-lg-6">

        <!-- Default Card Example -->
        <div class="card mb-4">
            <div class="card-header">
                Default Card Example
            </div>
            <div class="card-body">
                This card uses Bootstrap's default styling with no utility classes added. Global
                styles are the only things modifying the look and feel of this default card example.
            </div>
        </div>

        <!-- Basic Card Example -->
        <div class="card shadow mb-4">
            <div class="card-header py-3">
                <h6 class="m-0 font-weight-bold text-primary">Basic Card Example</h6>
            </div>
            <div class="card-body">
                The styling for this basic card example is created by using default Bootstrap
                utility classes. By using utility classes, the style of the card component can be
                easily modified with no need for any custom CSS!
            </div>
        </div>

    </div>
    <div class="col-lg-6">

        <!-- Default Card Example -->
        <div class="card mb-4">
            <div class="card-header">
                Default Card Example
            </div>
            <div class="card-body">
                This card uses Bootstrap's default styling with no utility classes added. Global
                styles are the only things modifying the look and feel of this default card example.
            </div>
        </div>

        <!-- Basic Card Example -->
        <div class="card shadow mb-4">
            <div class="card-header py-3">
                <h6 class="m-0 font-weight-bold text-primary">Basic Card Example</h6>
            </div>
            <div class="card-body">
                The styling for this basic card example is created by using default Bootstrap
                utility classes. By using utility classes, the style of the card component can be
                easily modified with no need for any custom CSS!
            </div>
        </div>

    </div>
</div>


{% endblock body %}

deliriumm/core/templates/core/events.html
{% extends 'core/layout_1.html' %}

{% block head %}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'core/style_index.css' %}">
<title>Eventos - Deliriumm Core</title>

{% endblock %}

{% block body %}

<h1>Eventos</h1>

<div class="card mb-4">

    <!-- Card Header -->
    <div class="card-header py-3">
        <div class="row justify-content-between">
            <div class="col-xl-4 col-md-6">
                <h6 class="m-0 font-weight-bold text-primary">Eventos</h6>
            </div>
        </div>
    </div>

    {% for event in events %}

    <div class="col-xl-3 col-md-6 mb-4">
        <div class="card border-left-primary shadow h-100 py-2">
            <div class="card-body">
                <div class="row no-gutters align-items-center">
                    <div class="col mr-2">
                        <div class="text-xs font-weight-bold text-primary mb-1">
                            <a href="">Evento: {{ event.name }}</a></div>
                        <div class="h5 mb-0 font-weight-bold text-gray-800">Estado: {{ event.get_status_display }}</div>
                    </div>
                    <div class="col-auto">
                        <i class="fas fa-calendar fa-2x text-gray-300"></i>
                    </div>
                </div>
            </div>
        </div>
    </div>
    
    {% endfor %}

</div>


<!-- Descripción Area -->

{% comment %} <div class="card-header py-3">
    <div class="text-start m-0 font-weight-bold text-primary">
        Descripción
    </div>
</div>
    <div class="card-body">
        <p class="mb-0">{{ ticketrequest.context}}</p>
    </div>
</div>
<div class="row"> {% endcomment %}


{% endblock body %}

deliriumm/core/templates/core/index.html
{% extends 'core/layout_1.html' %}

{% block head %}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'core/style_index.css' %}">
<title>Inicio - Deliriumm Core</title>

{% endblock %}

{% block body %}

<h1>CORE</h1>

<p>¡Bienvenid@, {{ user.first_name }}!</p>

{% if error_message %}
<h3>{{ error_message }}</h3>
{% endif %}

    {% if event %}
    <div class="card mb-4">
        <!-- Card Header -->
        <div class="card-header py-3">
            <div class="row justify-content-between">
                <div class="col-xl-4 col-md-6">
                    <h6 class="m-0 font-weight-bold text-primary">Evento: {{ event.name }} <mark>Estado: {{ event.get_status_display }}</mark></h6>
                </div>
                <div class="col-xl-3 col-md-6">
                    <div class="text-end ">
                        <a href=""><button type="button" class="btn btn-warning btn-sm">Admin</button></a>
                    </div>
                </div>
            </div>
        </div>


    <div class="row">
            {% comment %} col-xl-4 tamaño main {% endcomment %}
        <div class="col-xl-4 col-md-6 mb-4">
            <div class="card border-left-primary shadow h-100 py-2">
                <div class="card-body">
                    <div class="row no-gutters align-items-center">
                        <div class="col mr-2">
                            <div class="text-xs font-weight-bold text-primary mb-1">
                                Información del evento</div>
                            <div class="p mb-0 text-gray-800">
                                {{ event.datetime }}
                            </div>
                            <div class="p mb-0 text-gray-800">
                                <a href="{{ event.locationmapslink }}" target="_blank" rel="noopener noreferrer">Ubicación</a>
                            </div>
                            <div class="p mb-0 text-gray-800">
                                Precio: {{ event.price }} MXN
                            </div>
                        </div>
                        <div class="col-auto">
                            <i class="fas fa-calendar fa-2x text-gray-300"></i>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="col-xl-4 col-md-6 mb-4">
            <div class="card border-left-primary shadow h-100 py-2">
                <div class="card-body">
                    <div class="row no-gutters align-items-center">
                        <div class="col mr-2">
                            <div class="text-xs font-weight-bold text-primary mb-1">
                                Materiales</div>
                            {% for material in event.material_set.all %}
                            <div class="p mb-0 text-gray-800">
                                <a href="{% url 'core:dowload_material' material.pk %}" target="_blank" rel="noopener noreferrer">- {{material.description}}</a>
                            </div>
                            {% endfor %}
                        </div>
                        <div class="col-auto">
                            <i class="fas fa-calendar fa-2x text-gray-300"></i>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    {% endif %}



{% endblock body %}

deliriumm/core/templates/core/layout_1.html
<!DOCTYPE html>
<html lang="en">
    <head>
        {% load static %}

        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
        <link rel="stylesheet" type="text/css" href="{% static 'core/style_layout1.css' %}">
        
        {% block head %}
        {% endblock %}

    </head>
    <body>
      <header>

        <ul class="nav justify-content-center">
            <li class="nav-item">
              <a class="nav-link" aria-current="page" href="{% url 'core:index' %}" id="deliriumm">Deliriumm</a>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-expanded="false">Core</a>
              <ul class="dropdown-menu">
                <li><a class="dropdown-item" href="{% url 'core:index' %}">Dashboard</a></li>
                <li><a class="dropdown-item" href="{% url 'core:index' %}">Eventos</a></li>
                <li><a class="dropdown-item" href="{% url 'core:index' %}">Soporte</a></li>
                <li><hr class="dropdown-divider"></li>
                <li><a class="dropdown-item" href="{% url 'core:staff_view' %}">Staff</a></li>
                <li><hr class="dropdown-divider"></li>
                <li><a class="dropdown-item" href="{% url 'core:admin_view' %}">Admin</a></li>
              </ul>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'tickets:index' %}">Tickets</a>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-expanded="false">Mi Cuenta</a>
                <ul class="dropdown-menu">
                  <li><a class="dropdown-item disabled" href="#">¡Hola, {{ user.first_name }}!</a></li>
                  <li><a class="dropdown-item" href="{% url 'users:profile' %}">Perfil</a></li>
                  <li><a class="dropdown-item" href="{% url 'users:settings' %}">Configuración</a></li>
                  <li><hr class="dropdown-divider"></li>
                  <li><a class="dropdown-item" href="{% url 'users:logout' %}">Log Out</a></li>
                </ul>
              </li>
          </ul>

    </header>

        <div class="container">
        {% block body %}
        
        {% endblock body %}
      </div>

        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

    </body>
</html>