deliriumm/api/urls.py
from django.urls import path, include
from . import views
from rest_framework import routers


app_name = "api"

router = routers.DefaultRouter()
router.register(r'ticket', views.TicketViewSet)
router.register(r'ticketrequest', views.TicketRequestViewSet)
router.register(r'eventaccount', views.EventAccountViewSet)

urlpatterns = [
    path('', include(router.urls)),
    path('api-auth/', include('rest_framework.urls'))
]

deliriumm/core/urls.py
from django.urls import path

from . import views


app_name = "core"
urlpatterns = [
    path("", views.index, name="index"),
    path("dashboard/", views.dashboard, name="dashboard"),
    path("events/", views.events, name="events"),
    path("staff/", views.staff_view, name="staff_view"),
    path("admin/", views.admin_view, name="admin_view"),
    path("admin/rps_cash/", views.rps_cash_view, name="rps_cash_view"),
    path("admin/rps_all/", views.alltickets, name="rps_all"),
    path("material/dowload/<int:pk>", views.download_material, name="dowload_material"),
    path("material/delete/<int:pk>", views.delete_material, name="delete_material"),
    path("material/upload/", views.upload_material, name="upload_material")
]

deliriumm/deliriumm/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("users/", include("users.urls")),
    path("core/", include("core.urls")),
    path("", include("mainpage.urls")),
    path("core/tickets/", include("tickets.urls")),
    path("api/", include("api.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

deliriumm/tickets/urls.py
from django.urls import path

from . import views


app_name = "tickets"
urlpatterns = [
    path("", views.index, name="index"),
    path("my_tickets", views.my_tickets, name="my_tickets"),
    path("t/export/<str:hash>", views.temp_ticket_export, name="temp_ticket_export"),
    path("t/requestall/<str:requestid>", views.image_tickets, name="image_tickets"),
    path("t/image/<str:hash>", views.image_ticket, name="image_ticket"),
    path("t/download/<str:tickethash>", views.download_ticket, name="download_ticket"),
    path("r/<int:requestid>", views.request_view, name="request_view"),
    path("r/new", views.create_request_view, name="create_request_view"),
    path("r/new/create", views.new_ticket_request, name="new_ticket_request"),
    path("r/<int:requestid>/delete", views.delete_ticket_request, name="delete_ticket_request"),
    path("a/<int:requestid>", views.admin_request_view, name="admin_request_view"),
    path("a/<int:requestid>/ap", views.aprobar_request, name="aprobar_request"),
    path("a/<int:requestid>/re", views.rechazar_request, name="rechazar_request"),
    path("a/<int:requestid>/ar", views.archivar_request, name="archivar_request"),
    path("a/<int:requestid>/as", views.asignar_request, name="asignar_request"),
    path("a/<int:requestid>/togglecash", views.toggleCash, name="togglecash"),
]

deliriumm/users/urls.py
from django.urls import path

from . import views


app_name = "users"
urlpatterns = [
    path("", views.index, name="index"),
    path("login/", views.login_view, name="login"),
    path("logout/", views.logout_view, name="logout"),
    path("profile/", views.profile, name="profile"),
    path("settings/", views.settings, name="settings"),
    path("u/<str:username>", views.public_profile, name="public_profile"),
    path("register/", views.register, name="register")
]

deliriumm/tickets/models.py
from asyncio.unix_events import _UnixSelectorEventLoop
from numbers import Integral
from sys import maxsize
from tokenize import blank_re
from django.db import models
from django.forms import CharField
from core.models import Event
from django.contrib.auth.models import User

from users.models import UserCore

# Create your models here.


class TicketRequest(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    event = models.ForeignKey(Event, on_delete=models.CASCADE)
    context = models.CharField(max_length=300, blank=True)
    q_tickets = models.IntegerField(verbose_name="Tickets")
    reference = models.CharField(max_length=150, default="none")
    client = models.CharField(max_length=50, default="none")
    total = models.IntegerField(verbose_name="Total", default="0")
    created = models.DateTimeField(auto_now=True)
    staff_asigned = models.CharField(max_length=30, default="none")

    comprobante = models.FileField(upload_to='uploads/comprobantes/', blank=True)

    PAYMENTS = ( 
        ("CASH", "Efectivo"), 
        ("CARD", "Tarjeta"), 
        ("TRANSFER", "Transferencía"), 
        ("DEPOSIT", "Deposíto"), 
    ) 
    payment_method = models.CharField(
        max_length=20,
        choices=PAYMENTS,
        default='CASH',
    )

    cash_pay = models.BooleanField(blank=True, default=False)
    
    STATUS = ( 
        ("PE", "Pendiente"), 
        ("RE", "Rechazado"), 
        ("VA", "Aprobado"), 
        ("AR", "Archivado"), 
    ) 
    status = models.CharField(
        max_length=2,
        choices=STATUS,
        default='PE',
    )

    

    def __str__(self):
        return "#" + str(self.pk) + " - " + self.user.username + " " + self.status 

class Ticket(models.Model):

    hash = models.CharField(primary_key=True, verbose_name="Hash Id", max_length=200)
    client = models.CharField(max_length=50, default="none")
    ticketrequest = models.ForeignKey(TicketRequest, on_delete=models.CASCADE)


    user = models.ForeignKey(User, on_delete=models.CASCADE)
    event = models.ForeignKey(Event, on_delete=models.CASCADE)

    price = models.IntegerField(verbose_name="Price")

    status_export = models.BooleanField(default=True)

    use = models.BooleanField(default=False)
    
    def __str__(self):
        return "%s %s" % (self.hash, self.ticketrequest.pk)

class CommentTicketRequest(models.Model):
    ticketrequest = models.ForeignKey(TicketRequest, on_delete=models.CASCADE)
    event = models.ForeignKey(Event, on_delete=models.CASCADE)
    text = models.CharField(max_length=600)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    pub_date = models.DateTimeField(auto_now=True)

deliriumm/tickets/views.py
import os
from webbrowser import get
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.contrib.auth.models import User
import mimetypes

from users.models import UserCore

from .models import TicketRequest, Ticket
from core.models import Event
from hashlib import md5, sha256
import imgkit
from django.conf import settings


# Create your views here.

# -- MAIN --

#--------------------------------------------------------------------
def index(request):
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse("users:login"))
    usercore = get_object_or_404(UserCore, user=request.user)
    return render(request, "tickets/index.html",{
        "ticketspe": request.user.ticketrequest_set.all().filter(status="PE"),
        "ticketsap": request.user.ticketrequest_set.all().filter(status="VA"),
        "ticketsre": request.user.ticketrequest_set.all().filter(status="RE"),
        "last_ticket": usercore.last_ticket_request_see,

    })
#--------------------------------------------------------------------


#--------------------------------------------------------------------
def my_tickets(request):
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse("users:login"))
    usercore = get_object_or_404(UserCore, user=request.user)
    return render(request, "tickets/my_tickets.html",{
        "tickets": Ticket.objects.filter(user=request.user),
    })
#--------------------------------------------------------------------


#--------------------------------------------------------------------
# -- REQUEST -- 
#--------------------------------------------------------------------


#--------------------------------------------------------------------
def request_view(request, requestid):
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse("users:login"))
    if requestid == 0:
        return HttpResponseRedirect(reverse("tickets:index"))
    ticketrequest = get_object_or_404(TicketRequest, pk=requestid)
    usercore = get_object_or_404(UserCore, user=request.user)
    usercore.last_ticket_request_see = requestid
    usercore.save()

    status_display = ticketrequest.get_status_display()

    if ticketrequest.user == request.user or request.user.has_perm("users.can_view_admin") or request.user.has_perm("users.can_view_staff"):
        return render(request, "tickets/request_view.html", {
            "requestid": requestid,
            "ticketrequest": ticketrequest,
            "status_display": status_display,
            "ticketslist": Ticket.objects.filter(ticketrequest=requestid),
            "comments": ticketrequest.commentticketrequest_set.all()
        }) 


#--------------------------------------------------------------------


#--------------------------------------------------------------------
def create_request_view(request):
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse("users:login"))
    event_on_sell = get_object_or_404(Event, status="VE")
    return render(request, "tickets/create_request.html", {
        "event": event_on_sell
    })
#--------------------------------------------------------------------


#--------------------------------------------------------------------
def ticketCreate(request, event, totalp):
    if not request.POST["payment_method"] == "CASH":
        t = TicketRequest(user=request.user, event=event, context=request.POST["context"], 
        q_tickets=int(request.POST["q_tickets"]), reference=request.POST["reference"], 
        client=request.POST["client"], total=totalp, payment_method=request.POST["payment_method"], comprobante=request.FILES["comprobante"])
        return t
    elif request.POST["payment_method"] == "CASH":
        t = TicketRequest(user=request.user, event=event, context=request.POST["context"], 
        q_tickets=int(request.POST["q_tickets"]), reference=request.POST["reference"], 
        client=request.POST["client"], total=totalp, payment_method=request.POST["payment_method"], cash_pay=False)
        return t

def new_ticket_request(request):
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse("users:login"))
    event = get_object_or_404(Event, status="VE")
    if request.POST["q_tickets"]:
        totalp = int(request.POST["q_tickets"])*event.price
    else:
        totalp=0

    try:
        t = ticketCreate(request=request, event=event, totalp=totalp)
    except (BaseException):
        return render(request, "tickets/create_request.html",
        {
            "error_message": "¡Ha occurído un error!",
            "event": event
        })
    else:
        t.save()
        return HttpResponseRedirect(reverse("tickets:request_view", args=(t.pk,)))
#--------------------------------------------------------------------


#--------------------------------------------------------------------
def delete_ticket_request(request, requestid):
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse("users:login"))
    if request.POST:
        if request.POST.get('yes', False):
            tr = get_object_or_404(TicketRequest, pk=requestid)
            for ticket in tr.ticket_set.all():
                if os.path.exists(settings.MEDIA_ROOT + "/tickets/" + ticket.hash + '.jpg'):
                    os.remove(settings.MEDIA_ROOT + "/tickets/" + ticket.hash +'.jpg')
            if tr.comprobante:
                if os.path.exists(settings.MEDIA_ROOT + str(tr.comprobante)):
                    os.remove(settings.MEDIA_ROOT + str(tr.comprobante))



            get_object_or_404(TicketRequest, pk=requestid).delete()
            return HttpResponseRedirect(reverse("tickets:index"))
        if request.POST.get('not', False):
            return HttpResponseRedirect(reverse("tickets:request_view", args=(requestid,)))
    return render(request, "tickets/delete_ticket_request.html", {
        "requestid": requestid
    })
#--------------------------------------------------------------------


#--------------------------------------------------------------------
# -- ADMIN REQUESTS -- 
#--------------------------------------------------------------------


#--------------------------------------------------------------------
def admin_request_view(request, requestid):
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse("users:login"))
    if requestid == 0:
        return HttpResponseRedirect(reverse("tickets:index"))
    ticketrequest = get_object_or_404(TicketRequest, pk=requestid)
    usercore = get_object_or_404(UserCore, user=request.user)
    usercore.last_ticket_request_see = requestid
    usercore.save()

    status_display = ticketrequest.get_status_display()

    if request.user.has_perm("users.can_view_admin") or request.user.has_perm("users.can_view_staff") :
        return render(request, "tickets/adminrequest/admin_request_view.html", {
            "requestid": requestid,
            "ticketrequest": ticketrequest,
            "status_display": status_display,
            "ticketslist": Ticket.objects.filter(ticketrequest=requestid),
            "comments": ticketrequest.commentticketrequest_set.all()
        })
    else:
        return HttpResponseRedirect(reverse("tickets:request_view", args=(requestid,)))
#--------------------------------------------------------------------

#--------------------------------------------------------------------
# -- TICKETS -- 
#--------------------------------------------------------------------

#--------------------------------------------------------------------
def temp_ticket_export(request, hash):
    status_export = Ticket.objects.get(hash=hash)
    if status_export.status_export == True:
        return render(request, "tickets/ticket_export.html", {
            "hash": hash
        })
    else:
        return reverse("tickets:index")

def image_tickets(request, requestid):
    ticketrequest = get_object_or_404(TicketRequest, pk=requestid) 
    tickets = Ticket.objects.filter(ticketrequest=ticketrequest)
    return render(request, "tickets/image_tickets_request.html", {
        "requestid": requestid,
        "tickets": tickets,
        "ticketrequest": ticketrequest,
    })

def image_ticket(request, hash):
    ticket = get_object_or_404(Ticket, hash=hash)
    return render(request, "tickets/image_tickets.html", {
        "ticket": ticket,
    })

def download_ticket(request, tickethash):
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse("users:login"))

    # Define text file name
    filename = str(tickethash) + ".jpg"
    # Define the full file path
    filepath = settings.MEDIA_ROOT + 'tickets/' + filename
    # Open the file for reading content
    with open(filepath, 'rb') as f:
       path = f.read()
    # Set the mime type
    mime_type, _ = mimetypes.guess_type(filepath)
    # Set the return value of the HttpResponse
    response = HttpResponse(path, content_type=mime_type)
    # Set the HTTP header for sending to browser
    response['Content-Disposition'] = "attachment; filename=%s" % filename
    # Return the response value
    return response


def aprobar_request(request, requestid):
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse("users:login"))
    if requestid == 0:
        return HttpResponseRedirect(reverse("tickets:index"))
    ticketrequest = get_object_or_404(TicketRequest, pk=requestid)
    status_display = ticketrequest.get_status_display()

    if request.user.has_perm("users.can_view_admin") or request.user.has_perm("users.can_view_staff") :
        ticketrequest.status = "VA"
        ticketrequest.save()


        if ticketrequest.ticket_set.all():
            return HttpResponseRedirect(reverse("tickets:request_view", args=(requestid,)))

deliriumm/tickets/templates/tickets/index.html
{% extends 'tickets/layout_1.html' %}

{% block head %}
{% load static %}

<title>Tickets - Deliriumm Core</title>

{% endblock %}

{% block body %}

<h1>Tickets</h1>

{% if error_message %}
<h3>{{ error_message }}</h3>
{% endif %}

<div class="card shadow mb-4 ">
    <div class="card-body ">
        <ul class="nav justify-content-center">
            <li class="nav-item border-0">
                <a class="nav-link" href="{% url 'tickets:create_request_view' %}">Crear Request</a>
            </li>
            {% comment %} <li class="nav-item border-0">
                <a class="nav-link" href="">Ver mis Requests</a>
            </li>
            <li class="nav-item border-0">
                <a class="nav-link" href="{% url 'tickets:index' %}">Generar Tickets</a>
            </li> {% endcomment %}
            <li class="nav-item border-0">
                <a class="nav-link" href="{% url 'tickets:my_tickets' %}">Todos mis Tickets</a>
            </li>
            <li class="nav-item border-0">
                <a class="nav-link" href="{% url 'tickets:request_view' last_ticket %}">Última Request visitada</a>
            </li>
            <li class="nav-item border-0">
                <a class="nav-link" href="{% url 'tickets:index' %}">Soporte</a>
            </li>

        </ul>
    </div>
</div>


<div class="row">

    {% for ticket in ticketspe %}

    <div class="col-xl-3 col-md-6 mb-4">
        <div class="card border-left-primary shadow h-100 py-2">
            <div class="card-body">
                <div class="row no-gutters align-items-center">
                    <div class="col mr-2">
                        <div class="text-xs font-weight-bold text-primary mb-1">
                            <a href="{% url 'tickets:request_view' ticket.pk %}">Ticket Request #{{ ticket.pk }}</a></div>
                        <div class="h5 mb-0 font-weight-bold text-gray-800">Estado: {{ ticket.get_status_display }}</div>
                    </div>
                    <div class="col-auto">
                        <i class="fas fa-calendar fa-2x text-gray-300"></i>
                    </div>
                </div>
            </div>
        </div>
    </div>
    
    {% endfor %}
</div>

<div class="row">

    {% for ticket in ticketsap %}

    <div class="col-xl-3 col-md-6 mb-4">
        <div class="card border-left-primary shadow h-100 py-2">
            <div class="card-body">
                <div class="row no-gutters align-items-center">
                    <div class="col mr-2">
                        <div class="text-xs font-weight-bold text-primary mb-1">
                            <a href="{% url 'tickets:request_view' ticket.pk %}">Ticket Request #{{ ticket.pk }}</a></div>
                        <div class="h5 mb-0 font-weight-bold text-gray-800">Estado: {{ ticket.get_status_display }}</div>
                    </div>
                    <div class="col-auto">
                        <i class="fas fa-calendar fa-2x text-gray-300"></i>
                    </div>
                </div>
            </div>
        </div>
    </div>
    
    {% endfor %}

</div>

<div class="row">

    {% for ticket in ticketsre %}

    <div class="col-xl-3 col-md-6 mb-4">
        <div class="card border-left-primary shadow h-100 py-2">
            <div class="card-body">
                <div class="row no-gutters align-items-center">
                    <div class="col mr-2">
                        <div class="text-xs font-weight-bold text-primary mb-1">
                            <a href="{% url 'tickets:request_view' ticket.pk %}">Ticket Request #{{ ticket.pk }}</a></div>
                        <div class="h5 mb-0 font-weight-bold text-gray-800">Estado: {{ ticket.get_status_display }}</div>
                    </div>
                    <div class="col-auto">
                        <i class="fas fa-calendar fa-2x text-gray-300"></i>
                    </div>
                </div>
            </div>
        </div>
    </div>
    
    {% endfor %}

</div>


{% endblock body %}

deliriumm/tickets/templates/tickets/layout_1.html
<!DOCTYPE html>
<html lang="en">
    <head>
        {% load static %}

        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
        <link rel="stylesheet" type="text/css" href="{% static 'tickets/style_layout1.css' %}">
        
        {% block head %}
        {% endblock %}

    </head>
    <body>
      <header>

        <ul class="nav justify-content-center">
            <li class="nav-item">
              <a class="nav-link" aria-current="page" href="{% url 'core:index' %}" id="deliriumm">Deliriumm</a>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-expanded="false">Core</a>
              <ul class="dropdown-menu">
                <li><a class="dropdown-item" href="{% url 'core:index' %}">Dashboard</a></li>
                <li><a class="dropdown-item" href="{% url 'core:index' %}">Eventos</a></li>
                <li><a class="dropdown-item" href="{% url 'core:index' %}">Soporte</a></li>
                <li><hr class="dropdown-divider"></li>
                <li><a class="dropdown-item" href="{% url 'core:staff_view' %}">Staff</a></li>
                <li><hr class="dropdown-divider"></li>
                <li><a class="dropdown-item" href="{% url 'core:admin_view' %}">Admin</a></li>
              </ul>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'tickets:index' %}">Tickets</a>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-expanded="false">Mi Cuenta</a>
                <ul class="dropdown-menu">
                  <li><a class="dropdown-item disabled" href="#">¡Hola, {{ user.first_name }}!</a></li>
                  <li><a class="dropdown-item" href="{% url 'users:profile' %}">Perfil</a></li>
                  <li><a class="dropdown-item" href="{% url 'users:settings' %}">Configuración</a></li>
                  <li><hr class="dropdown-divider"></li>
                  <li><a class="dropdown-item" href="{% url 'users:logout' %}">Log Out</a></li>
                </ul>
              </li>
          </ul>

    </header>

        <div class="container">
        {% block body %}
        
        {% endblock body %}
      </div>

        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

    </body>
</html>

deliriumm/tickets/templates/tickets/request_view.html
{% extends 'tickets/layout_1.html' %}

{% block head %}
{% load static %}
<title>Ticket #{{ requestid }} - Deliriumm Core</title>

{% endblock %}

{% block body %}

<h1>Tickets</h1>


{% if error_message %}
<h3>{{ error_message }}</h3>
{% endif %}

<!-- Card 1 -->
    <div class="card mb-4">
        <!-- Card Header -->
        <div class="card-header py-3">
            <div class="row justify-content-between">
                <div class="col-xl-4 col-md-6">
                    <h6 class="m-0 font-weight-bold text-primary">Ticket Request #{{ requestid }} <mark>Estado: {{ status_display }}</mark></h6>
                </div>
                <div class="col-xl-3 col-md-6">
                    <div class="text-end ">
                        <a href="{% url 'tickets:admin_request_view' requestid %}"><button type="button" class="btn btn-warning btn-sm">Admin</button></a>
                        <a href="{% url 'tickets:delete_ticket_request' requestid %}"><button type="button" class="btn btn-danger btn-sm">Borrar Request</button></a>
                        
                    </div>
                </div>
            </div>
        </div>

<!-- Part -->

        <div class="row">
            {% comment %} col-xl-4 tamaño main {% endcomment %}
        <div class="col-xl-4 col-md-6 mb-4">
            <div class="card border-left-primary shadow h-100 py-2">
                <div class="card-body">
                    <div class="row no-gutters align-items-center">
                        <div class="col mr-2">
                            <div class="text-xs font-weight-bold text-primary mb-1">
                                Información del evento</div>
                            <div class="p mb-0 text-gray-800">
                                {{ ticketrequest.event.name }}
                            </div>
                            <div class="p mb-0 text-gray-800">
                                {{ ticketrequest.event.datetime }}
                            </div>
                        </div>
                        <div class="col-auto">
                            <i class="fas fa-calendar fa-2x text-gray-300"></i>
                        </div>
                    </div>
                </div>
            </div>
        </div>

<!-- Part -->

        <div class="col-xl-3 col-md-6 mb-4">
            <div class="card border-left-primary shadow h-100 py-2">
                <div class="card-body">
                    <div class="row no-gutters align-items-center">
                        <div class="col mr-2">
                            <div class="text-xs font-weight-bold text-primary mb-1">
                                Tickets</div>
                            <div class="p mb-0 text-gray-800">
                                Cantidad: {{  ticketrequest.q_tickets }}
                            </div>
                            <div class="p mb-0 text-gray-800">
                                Total: {{  ticketrequest.total }} MXN
                            </div>
                        </div>
                        <div class="col-auto">
                            <i class="fas fa-calendar fa-2x text-gray-300"></i>
                        </div>
                    </div>
                </div>
            </div>
        </div>

<!-- Part -->

        <div class="col-xl-5 col-md-6 mb-4">
            <div class="card border-left-primary shadow h-100 py-2">
                <div class="card-body">
                    <div class="row no-gutters align-items-center">
                        <div class="col mr-2">
                            <div class="text-xs font-weight-bold text-primary mb-1">
                                Pago - {{ ticketrequest.get_payment_method_display }}</div>
                            {% if ticketrequest.payment_method == "CASH" %}
                            <div class="p mb-0 text-gray-800">
                                Comprobante: Efectivo
                            </div>
                            {% endif %}
                            {% if not ticketrequest.payment_method == "CASH" %}
                            <div class="p mb-0 text-gray-800">
                                Comprobante: <a href="/media/{{ticketrequest.comprobante}}" target="_blank" rel="noopener noreferrer">Ver Comprobante</a>
                            </div>
                           {% endif %}
                            <div class="p mb-0 text-gray-800">
                                Referencía: {{  ticketrequest.reference }}
                            </div>
                        </div>
                        <div class="col-auto">
                            <i class="fas fa-calendar fa-2x text-gray-300"></i>
                        </div>
                    </div>
                </div>
            </div>
        </div>


<!-- Part -->

        <div class="col-xl-4 col-md-6 mb-4">
            <div class="card border-left-primary shadow h-100 py-2">
                <div class="card-body">
                    <div class="row no-gutters align-items-center">
                        <div class="col mr-2">
                            <div class="text-xs font-weight-bold text-primary mb-1">
                                Request</div>
                            <div class="p mb-0 text-gray-800">
                                Cliente: {{ ticketrequest.client }}
                            </div>
                            <div class="p mb-0 text-gray-800">
                                Request: {{ ticketrequest.created }}
                            </div>
                        </div>
                        <div class="col-auto">
                            <i class="fas fa-calendar fa-2x text-gray-300"></i>
                        </div>
                    </div>
                </div>
            </div>
        </div>

<!-- Part -->

        <div class="col-xl-3 col-md-6 mb-4">
            <div class="card border-left-primary shadow h-100 py-2">
                <div class="card-body">
                    <div class="row no-gutters align-items-center">
                        <div class="col mr-2">
                            <div class="text-xs font-weight-bold text-primary mb-1">
                                Request</div>
                            <div class="p mb-0 text-gray-800">
                                Hecha por: @{{ ticketrequest.user.username }}
                            </div>
                            {% if ticketrequest.staff_asigned != "none" %}
                            <div class="p mb-0 text-gray-800">
                                Staff asignado: @{{ ticketrequest.staff_asigned }}
                            </div>
                            {% endif %}
                        </div>
                        <div class="col-auto">
                            <i class="fas fa-calendar fa-2x text-gray-300"></i>
                        </div>
                    </div>
                </div>
            </div>
        </div>

<!-- Part -->
{% if ticketrequest.status == "VA" or ticketrequest.status == "AR" %}
<div class="col-xl-4 col-md-6 mb-4">
    <div class="card border-left-primary shadow h-100 py-2">
        <div class="card-body">
            <div class="row no-gutters align-items-center">
                <div class="col mr-2">
                    <div class="text-xs font-weight-bold text-primary mb-1">
                        Tickets - <a href="{% url 'tickets:image_tickets' requestid %}">Guardar en Imagen</a></div>
                    {% for ticket in ticketslist %}
                    <div class="p mb-0 text-gray-800">
                        <a href="{% url 'tickets:image_ticket' ticket.hash %}">Ticket #{{ ticket.hash }}</a> 
                    </div>
                    {% endfor %}
                </div>
                <div class="col-auto">
                    <i class="fas fa-calendar fa-2x text-gray-300"></i>
                </div>
            </div>
        </div>
    </div>
</div>
{% endif %}

<!-- Descripción Area -->
    </div>
    <div class="card-header py-3">
        <div class="text-start m-0 font-weight-bold text-primary">
            Comentario
        </div>
    </div>
        <div class="card-body">
            <p class="mb-0">{{ ticketrequest.context}}</p>
        </div>
    </div>




<!-- For Loop Comments (conv) -->
{% if comments %}
<div class="card mb-4">
{% for comment in comments %}
     <div class="card-body">
            <h6>@{{ comment.user.username }}</h6>
            <p class="mb-0">{{ comment.text }}</p>
    </div>
{% endfor %}
    </div>
{% endif %}




{% endblock body %}